Add CI (#1)
* Try this

* Change ci run conditions

* fix

* oi

* oi

* oi

* oi

* ope

* ope

* ope

* ope

* ope

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -2,26 +2,49 @@ name: CI
 
 on:
   push:
-  pull_request:
     branches: [main]
+  pull_request: {}
 
 jobs:
-  main:
+  lints:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: wyvox/action-setup-pnpm@v3
+      - run: pnpm lint
+
+  test_success:
     strategy:
       matrix:
         os:
           - ubuntu-latest
-          - windows-latest
+          # - windows-latest
           - macos-latest
-        node:
-          - latest
-          - lts/*
-          - 18
     runs-on: ${{ matrix.os }}
     steps:
       - uses: actions/checkout@v4
-      - uses: wyvox/action-setup-pnpm@v3
       - uses: ./
-        with:
-          node-version: ${{ matrix.node }}
-      - run: pnpm lint:fix
+
+  test_failure:
+    strategy:
+      matrix:
+        os:
+          - ubuntu-latest
+          # - windows-latest
+          - macos-latest
+    runs-on: ${{ matrix.os }}
+    steps:
+      - uses: actions/checkout@v4
+      - run: rm .prettierignore
+      - uses: ./
+        id: self
+        continue-on-error: true
+      - if: always()
+        run: |
+          if [[ "${{ steps.self.outcome }}" == "failure" ]]; then
+            echo "Successfully failed"
+            exit 0;
+          else
+            echo "Unsuccessfully failed. Expected failure."
+            exit 1
+          fi
